Download ffmpeg binary from kuende gcs instead of nvartolomei bintray

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -29,10 +29,19 @@ mkdir -p $output_dir
 mkdir -p $temp_app_dir
 
 echo "Downloading ffmpeg and unpacking" | indent
-curl -sL https://dl.bintray.com/nvartolomei/heroku-buildpack-ffmpeg/ffmpeg-3.1.4.tar.gz | tar xz -C $output_dir
+
+FFMPEG_URL="gs://kuende-staging1-bin/ffmpeg/ffmpeg.tar.gz"
+GOOGLE_APPLICATION_CREDENTIALS=$VESSEL_GOOGLE_APPLICATION_CREDENTIALS vessel-downloader ${FFMPEG_URL} /tmp/ffmpeg.tgz
 
 if [ $? != 0 ]; then
-  echo "Error downloading ffmpeg and unpacking to build dir" | indent
+  echo "Error downloading ffmpeg" | indent
+  exit 1
+fi
+
+tar xzf /tmp/ffmpeg.tgz -C $output_dir
+
+if [ $? != 0 ]; then
+  echo "Error unpacking to build dir" | indent
   exit 1
 fi
 
